"use strict";

// The name of your game, no spaces or special characters.
var name = "MilfyCity";

// The version of the cache, changing this will force everything to be cached
// again.
var version = "0.1.0";

var files = [

	// General Files
	"manifest.json",

	// HTML Files
	// "index.html",

	// Style Sheets
	"style/font-awesome.min.css",
	"style/kayros.min.css",
	"style/animate.min.css",
	"style/csshake.min.css",
	"style/monogatari.css",
	// "style/main.css",

	// JavaScript Files
	"js/polyfill.min.js",
	"js/particles.min.js",
	"js/jquery.min.js",
	"js/artemis.min.js",
	"js/typed.min.js",
	"js/monogatari.js",
	"js/strings.js",
	// "js/options.js",
	// "js/storage.js",
	// "js/script.js",
	// "js/main.js"

	// Fonts
	"fonts/fontawesome-webfont.eot",
	"fonts/fontawesome-webfont.svg",
	"fonts/fontawesome-webfont.ttf",
	"fonts/fontawesome-webfont.woff",
	"fonts/fontawesome-webfont.woff2",
	"fonts/FontAwesome.otf",

	// App Images
	"img/favicon.ico",
	"img/icons/icon_48x48.png",
	"img/icons/icon_60x60.png",
	"img/icons/icon_70x70.png",
	"img/icons/icon_76x76.png",
	"img/icons/icon_96x96.png",
	"img/icons/icon_128x128.png",
	"img/icons/icon_150x150.png",
	"img/icons/icon_152x152.png",
	"img/icons/icon_167x167.png",
	"img/icons/icon_180x180.png",
	"img/icons/icon_192x192.png",
	"img/icons/icon_310x310.png",
	"img/icons/icon_512x512.png"

	// Scene Images
	"img/scenes/Morning.jpg",
	"img/scenes/N_Morning.jpg",
	"img/scenes/SD_Night.jpg",
	"img/scenes/SD_Afternoon.jpg",
	"img/scenes/OH_later.jpg",
	"img/scenes/SD_E.jpg",
	"img/scenes/ND_A.jpg",

	"img/scenes/bi1.jpg",
	"img/scenes/bi2.jpg",
	"img/scenes/bi3a.jpg",
	"img/scenes/bi3b.jpg",
	"img/scenes/bi4.jpg",
	"img/scenes/i1.jpg",
	"img/scenes/i2.jpg",
	"img/scenes/i3.jpg",
	"img/scenes/i4.jpg",
	"img/scenes/i5.jpg",
	"img/scenes/i6.jpg",
	"img/scenes/i7.jpg",
	"img/scenes/i8.jpg",
	"img/scenes/i9.jpg",
	"img/scenes/i10.jpg",
	"img/scenes/i11.jpg",
	"img/scenes/i12.jpg",
	"img/scenes/i13.jpg",
	"img/scenes/i14.jpg",
	"img/scenes/i15.jpg",
	"img/scenes/i16.jpg",
	"img/scenes/i17.jpg",
	"img/scenes/i18.jpg",
	"img/scenes/i19.jpg",
	"img/scenes/i20.jpg",
	"img/scenes/i21.jpg",
	"img/scenes/i22.jpg",
	"img/scenes/i23.jpg",
	"img/scenes/i24.jpg",
	"img/scenes/i25.jpg",
	"img/scenes/i26a.jpg",
	"img/scenes/i26b.jpg",
	"img/scenes/i27.jpg",
	"img/scenes/i28.jpg",
	"img/scenes/i29.jpg",
	"img/scenes/i30.jpg",
	"img/scenes/i31.jpg",
	"img/scenes/i32.jpg",
	"img/scenes/i33.jpg",
	"img/scenes/i34.jpg",
	"img/scenes/i35.jpg",
	"img/scenes/i36.jpg",
	"img/scenes/i37.jpg",
	"img/scenes/i38.jpg",
	"img/scenes/i39.jpg",
	"img/scenes/i40.jpg",
	"img/scenes/i41.jpg",
	"img/scenes/i42.jpg",
	"img/scenes/i43.jpg",
	"img/scenes/i44.jpg",
	"img/scenes/i45.jpg",
	"img/scenes/i46.jpg",
	"img/scenes/i47.jpg",
	"img/scenes/i48.jpg",
	"img/scenes/i49.jpg",
	"img/scenes/i50.jpg",
	"img/scenes/i51.jpg",
	"img/scenes/i52.jpg",
	"img/scenes/i53.jpg",
	"img/scenes/i54.jpg",
	"img/scenes/Character_Choice.jpg",
	"img/scenes/M_S0_p1.jpg",
	"img/scenes/M_S0_p2.jpg",
	"img/scenes/M_S0_p2a.jpg",
	"img/scenes/M_S0_p3.jpg",
	"img/scenes/M_S0_p4.jpg",
	"img/scenes/M_S0_p5.jpg",

	"img/scenes/M_S1_p1.jpg",
	"img/scenes/M_S1_p2.jpg",
	"img/scenes/M_S1_p3.jpg",
	"img/scenes/M_S1_p4.jpg",
	"img/scenes/M_S1_p5.jpg",
	"img/scenes/M_S1_p6.jpg",
	"img/scenes/M_S1_p7.jpg",
	"img/scenes/M_S1_p8.jpg",
	"img/scenes/M_S1_p9.jpg",
	"img/scenes/M_S1_p10.jpg",

	"img/scenes/M_S2_p1.jpg",
	"img/scenes/M_S2_p2.jpg",
	"img/scenes/M_S2_p3.jpg",
	"img/scenes/M_S2_p4.jpg",
	"img/scenes/M_S2_p5.jpg",
	"img/scenes/M_S2_p6.jpg",
	"img/scenes/M_S2_p7.jpg",

	"img/scenes/M_NS1_p1.jpg",
	"img/scenes/M_NS1_p2.jpg",
	"img/scenes/M_NS1_p3.jpg",
	"img/scenes/M_NS1_p4.jpg",
	"img/scenes/M_NS1_p5.jpg",
	"img/scenes/M_NS1_p6.jpg",
	"img/scenes/M_NS1_p7.jpg",

	"img/scenes/M_Book_p1.jpg",
	
	"img/scenes/M_Book_p3.jpg",
	"img/scenes/M_Book_p4.jpg",

	"img/scenes/M_MS3_p1.jpg",
	"img/scenes/M_MS3_p2.jpg",
	"img/scenes/M_MS3_p3.jpg",
	"img/scenes/M_MS3_p4.jpg",
	"img/scenes/M_MS3_p5.jpg",
	"img/scenes/M_MS3_p6.jpg",
	"img/scenes/M_MS3_p7.jpg",
	"img/scenes/M_MS3_p8.jpg",
	"img/scenes/M_MS3_p9.jpg",
	"img/scenes/M_MS3_p10.jpg",
	"img/scenes/M_MS3_p11.jpg",
	"img/scenes/M_MS3_p12.jpg",
	"img/scenes/M_MS3_p13.jpg",
	"img/scenes/M_MS3_p14.jpg",
	"img/scenes/M_MS3_p15.jpg",

	"img/scenes/M_MS5_p1.jpg",
	"img/scenes/M_MS5_p2.jpg",
	"img/scenes/M_MS5_p3.jpg",
	"img/scenes/M_MS5_p4.jpg",
	"img/scenes/M_MS5_p5.jpg",
	"img/scenes/M_MS5_p6.jpg",
	"img/scenes/M_MS5_p7.jpg",
	"img/scenes/M_MS5_p8.jpg",
	"img/scenes/M_MS5_p9.jpg",
	"img/scenes/M_MS5_p10.jpg",
	"img/scenes/M_MS5_p11.jpg",
	"img/scenes/M_MS5_p12.jpg",
	"img/scenes/M_MS5_p13.jpg",
	"img/scenes/M_MS5_p14.jpg",
	"img/scenes/M_MS5_p15.jpg",
	"img/scenes/M_MS5_p16.jpg",
	"img/scenes/M_MS5_p17.jpg",
	"img/scenes/M_MS5_p18.jpg",
	"img/scenes/M_MS5_p19.jpg",
	"img/scenes/M_MS5_p20.jpg",
	"img/scenes/M_MS5_p21.jpg",
	"img/scenes/M_MS5_p22.jpg",
	"img/scenes/M_MS5_p23.jpg",
	"img/scenes/M_MS5_p24.jpg",
	"img/scenes/M_MS5_p25.jpg",
	"img/scenes/M_MS5_p26.jpg",
	"img/scenes/M_MS5_p27.jpg",

	"img/scenes/M_AS1_p1.jpg",
	"img/scenes/M_AS1_p2.jpg",
	"img/scenes/M_AS1_p3.jpg",
	"img/scenes/M_AS1_p4.jpg",
	"img/scenes/M_AS1_p5.jpg",
	"img/scenes/M_AS1_p6.jpg",
	"img/scenes/M_AS1_p7.jpg",
	"img/scenes/M_AS1_p8.jpg",
	"img/scenes/M_AS1_p9.jpg",
	"img/scenes/M_AS1_p10.jpg",
	"img/scenes/M_AS1_p11.jpg",
	"img/scenes/M_AS1_p12.jpg",
	"img/scenes/M_AS1_p13.jpg",
	"img/scenes/M_AS1_p14.jpg",
	"img/scenes/M_AS1_p15.jpg",

	"img/scenes/M_MS6_p1.jpg",
	"img/scenes/M_MS6_p2.jpg",
	"img/scenes/M_MS6_p3.jpg",
	"img/scenes/M_MS6_p4.jpg",
	"img/scenes/M_MS6_p5.jpg",
	"img/scenes/M_MS6_p6.jpg",
	"img/scenes/M_MS6_p7.jpg",
	"img/scenes/M_MS6_p8.jpg",
	"img/scenes/M_MS6_p9.jpg",
	"img/scenes/M_MS6_p10.jpg",
	"img/scenes/M_MS6_p11.jpg",
	"img/scenes/M_MS6_p12.jpg",
	"img/scenes/M_MS6_p13.jpg",
	"img/scenes/M_MS6_p13a.jpg",
	"img/scenes/M_MS6_p14.jpg",
	"img/scenes/M_MS6_p15.jpg",
	"img/scenes/M_MS6_p16.jpg",
	"img/scenes/M_MS6_p16a.jpg",
	"img/scenes/M_MS6_p17.jpg",
	"img/scenes/M_MS6_p18.jpg",
	"img/scenes/M_MS6_p19a.jpg",
	"img/scenes/M_MS6_p19b.jpg",
	"img/scenes/M_MS6_p19c.jpg",
	"img/scenes/M_MS6_p20.jpg",
	"img/scenes/M_MS6_p21.jpg",
	"img/scenes/M_MS6_p22.jpg",
	"img/scenes/M_MS6_p23.jpg",
	"img/scenes/M_MS6_p24.jpg",
	"img/scenes/M_MS6_p25.jpg",
	"img/scenes/M_MS6_p26.jpg",
	"img/scenes/M_MS6_p27.jpg",
	"img/scenes/M_MS6_p28.jpg",
	"img/scenes/M_MS6_p29.jpg",
	"img/scenes/M_MS6_p30.jpg",

	"img/scenes/M_AS2_p1.jpg",
	"img/scenes/M_AS2_p2.jpg",
	"img/scenes/M_AS2_p3.jpg",
	"img/scenes/M_AS2_p4.jpg",
	"img/scenes/M_AS2_p5.jpg",
	"img/scenes/M_AS2_p6.jpg",
	"img/scenes/M_AS2_p7.jpg",
	"img/scenes/M_AS2_p8.jpg",
	"img/scenes/M_AS2_p9.jpg",
	"img/scenes/M_AS2_p10.jpg",
	"img/scenes/M_AS2_p11.jpg",
	"img/scenes/M_AS2_p12.jpg",
	"img/scenes/M_AS2_p13.jpg",
	"img/scenes/M_AS2_p14.jpg",
	"img/scenes/M_AS2_p15.jpg",
	"img/scenes/M_AS2_p16.jpg",
	"img/scenes/M_AS2_p17.jpg",
	"img/scenes/M_AS2_p18.jpg",
	"img/scenes/M_AS2_p19.jpg",
	"img/scenes/M_AS2_p19a.jpg",
	"img/scenes/M_AS2_p20.jpg",
	"img/scenes/M_AS2_p21.jpg",

	"img/scenes/M_NS3_p1.jpg",
	"img/scenes/M_NS3_p2.jpg",
	"img/scenes/M_NS3_p3.jpg",
	"img/scenes/M_NS3_p4.jpg",
	"img/scenes/M_NS3_p5.jpg",
	"img/scenes/M_NS3_p6.jpg",
	"img/scenes/M_NS3_p7.jpg",
	"img/scenes/M_NS3_p8.jpg",
	"img/scenes/M_NS3_p9.jpg",
	"img/scenes/M_NS3_p10.jpg",
	"img/scenes/M_NS3_p11.jpg",
	"img/scenes/M_NS3_p12.jpg",

	"img/scenes/M_NS3_Blow_p0.jpg",
	"img/scenes/M_NS3_Blow_p1.jpg",
	"img/scenes/M_NS3_Blow_p2.jpg",
	"img/scenes/M_NS3_Blow_p3.jpg",
	"img/scenes/M_NS3_Blow_p4.jpg",
	"img/scenes/M_NS3_Blow_p5.jpg",
	"img/scenes/M_NS3_Blow_p6.jpg",
	"img/scenes/M_NS3_Blow_p7.jpg",
	"img/scenes/M_NS3_Blow_p8.jpg",
	"img/scenes/M_NS3_Blow_p9.jpg",
	"img/scenes/M_NS3_Blow_p10.jpg",
	"img/scenes/M_NS3_Blow_p11.jpg",
	"img/scenes/M_NS3_Blow_p12.jpg",
	"img/scenes/M_NS3_Blow_p13a.jpg",
	"img/scenes/M_NS3_Blow_p13b.jpg",
	"img/scenes/M_NS3_Blow_p13c.jpg",
	"img/scenes/M_NS3_Blow_p14a.jpg",

	"img/scenes/M_NS3_Foot_p1.jpg",
	"img/scenes/M_NS3_Foot_p2.jpg",
	"img/scenes/M_NS3_Foot_p3.jpg",
	"img/scenes/M_NS3_Foot_p4.jpg",
	"img/scenes/M_NS3_Foot_p5.jpg",
	"img/scenes/M_NS3_Foot_p6.jpg",
	"img/scenes/M_NS3_Foot_p7.jpg",
	"img/scenes/M_NS3_Foot_p8.jpg",
	"img/scenes/M_NS3_Foot_p9.jpg",
	"img/scenes/M_NS3_Foot_p10.jpg",
	"img/scenes/M_NS3_Foot_p11.jpg",
	"img/scenes/M_NS3_Foot_p12.jpg",
	"img/scenes/M_NS3_Foot_p12a.jpg",
	"img/scenes/M_NS3_Foot_p13.jpg",

	"img/scenes/C_MS1_p1.jpg",
	"img/scenes/C_MS1_p2.jpg",
	"img/scenes/C_MS1_p2a.jpg",
	"img/scenes/C_MS1_p3.jpg",
	"img/scenes/C_MS1_p4.jpg",
	"img/scenes/C_MS1_p5.jpg",
	"img/scenes/C_MS1_p6.jpg",

	"img/scenes/C_ES1_p1.jpg",
	"img/scenes/C_ES1_p2.jpg",
	"img/scenes/C_ES1_p3.jpg",
	"img/scenes/C_ES1_p4.jpg",

	"img/scenes/C_MS2_p1.jpg",
	"img/scenes/C_MS2_p2.jpg",
	"img/scenes/C_MS2_p3.jpg",
	"img/scenes/C_MS2_p4.jpg",

	"img/scenes/C_MS3_p1.jpg",
	"img/scenes/C_MS3_p2.jpg",
	"img/scenes/C_MS3_p3.jpg",
	"img/scenes/C_MS3_p4.jpg",

	"img/scenes/C_AS1_p1.jpg",
	"img/scenes/C_AS1_p2.jpg",
	"img/scenes/C_AS1_p3.jpg",
	"img/scenes/C_AS1_p4a.jpg",

	"img/scenes/C_AS1a_p1.jpg",
	"img/scenes/C_AS1a_p2.jpg",

	"img/scenes/C_AS2_p1.jpg",
	"img/scenes/C_AS2_p2.jpg",
	"img/scenes/C_AS2_p3.jpg",
	"img/scenes/C_AS2_p4.jpg",
	"img/scenes/C_AS2_p5.jpg",
	"img/scenes/C_AS2_p6.jpg",
	"img/scenes/C_AS2_p7.jpg",
	"img/scenes/C_AS2_p8.jpg",
	"img/scenes/C_AS2_p9.jpg",
	"img/scenes/C_AS2_p10.jpg",
	"img/scenes/C_AS2_p11.jpg",
	"img/scenes/C_AS2_p12.jpg",
	"img/scenes/C_AS2_p13.jpg",
	"img/scenes/C_AS2_p14.jpg",

	"img/scenes/C_ES2_p1.jpg",
	"img/scenes/C_ES2_p2.jpg",
	"img/scenes/C_ES2_p3.jpg",

	"img/scenes/C_NS1_p1.jpg",
	"img/scenes/C_NS1_p2.jpg",

	"img/scenes/C_NS1_Mouth_p1.jpg",
	"img/scenes/C_NS1_Mouth_p2.jpg",
	"img/scenes/C_NS1_Mouth_p3.jpg",
	"img/scenes/C_NS1_Mouth_p4.jpg",
	"img/scenes/C_NS1_Mouth_p5.jpg",
	"img/scenes/C_NS1_Mouth_p6.jpg",
	"img/scenes/C_NS1_Mouth_p7.jpg",
	"img/scenes/C_NS1_Mouth_p8.jpg",

	"img/scenes/C_NS1_Feet_p1.jpg",
	"img/scenes/C_NS1_Feet_p2.jpg",
	"img/scenes/C_NS1_Feet_p3.jpg",
	"img/scenes/C_NS1_Feet_p4.jpg",
	"img/scenes/C_NS1_Feet_p5.jpg",

	"img/scenes/C_NS1_Tits_p1.jpg",
	"img/scenes/C_NS1_Tits_p2.jpg",
	"img/scenes/C_NS1_Tits_p3.jpg",
	"img/scenes/C_NS1_Tits_p4.jpg",
	"img/scenes/C_NS1_Tits_p5.jpg",
	"img/scenes/C_NS1_Tits_p6.jpg",
	"img/scenes/C_NS1_Tits_p7.jpg",

	"img/scenes/C_NS1_Ass_p1.jpg",
	"img/scenes/C_NS1_Ass_p2.jpg",
	"img/scenes/C_NS1_Ass_p3.jpg",
	"img/scenes/C_NS1_Ass_p4.jpg",
	"img/scenes/C_NS1_Ass_p5.jpg",
	"img/scenes/C_NS1_Ass_p6.jpg",
	"img/scenes/C_NS1_Ass_p7.jpg",
	"img/scenes/C_NS1_Ass_p8.jpg",

	"img/scenes/C_MS4_p1.jpg",
	"img/scenes/C_MS4_p2.jpg",
	"img/scenes/C_MS4_p3.jpg",

	"img/scenes/C_ES3_p1.jpg",
	"img/scenes/C_ES3_p2.jpg",
	"img/scenes/C_ES3_p3.jpg",
	"img/scenes/C_ES3_p4.jpg",
	"img/scenes/C_ES3_p5.jpg",
	"img/scenes/C_ES3_p6.jpg",
	"img/scenes/C_ES3_p7.jpg",
	"img/scenes/C_ES3_p8.jpg",
	"img/scenes/C_ES3_p9.jpg",
	"img/scenes/C_ES3_p10.jpg",
	"img/scenes/C_ES3_p11.jpg",
	"img/scenes/C_ES3_p12.jpg",
	"img/scenes/C_ES3_p13.jpg",
	"img/scenes/C_ES3_p14.jpg",
	"img/scenes/C_ES3_p15.jpg",
	"img/scenes/C_ES3_p16.jpg",
	"img/scenes/C_ES3_p17.jpg",
	"img/scenes/C_ES3_p18.jpg",
	"img/scenes/C_ES3_p19.jpg",
	"img/scenes/C_ES3_p20.jpg",
	"img/scenes/C_ES3_p21.jpg",
	"img/scenes/C_ES3_p22.jpg",
	"img/scenes/C_ES3_p23.jpg",
	"img/scenes/C_ES3_p24.jpg",
	"img/scenes/C_ES3_p25.jpg",
	"img/scenes/C_ES3_p25a.jpg",
	"img/scenes/C_ES3_p26.jpg",
	"img/scenes/C_ES3_p27.jpg",
	"img/scenes/C_ES3_p28.jpg",

	"img/scenes/C_AS3_p1.jpg",
	"img/scenes/C_AS3_p2.jpg",
	"img/scenes/C_AS3_p3.jpg",
	"img/scenes/C_AS3_p4.jpg",
	"img/scenes/C_AS3_p5.jpg",
	"img/scenes/C_AS3_p6.jpg",
	"img/scenes/C_AS3_p7.jpg",
	"img/scenes/C_AS3_p8.jpg",
	"img/scenes/C_AS3_p9.jpg",
	"img/scenes/C_AS3_p10.jpg",
	"img/scenes/C_AS3_p11.jpg",
	"img/scenes/C_AS3_p12.jpg",
	"img/scenes/C_AS3_p13.jpg",
	"img/scenes/C_AS3_p14.jpg",
	"img/scenes/C_AS3_p15.jpg",
	"img/scenes/C_AS3_p16.jpg",
	"img/scenes/C_AS3_p17.jpg",
	"img/scenes/C_AS3_p18.jpg",
	"img/scenes/C_AS3_p19.jpg",
	"img/scenes/C_AS3_p20.jpg",
	"img/scenes/C_AS3_p21.jpg",
	"img/scenes/C_AS3_p22.jpg",

	"img/scenes/C_ES4_p1.jpg",
	"img/scenes/C_ES4_p2.jpg",
	"img/scenes/C_ES4_p3.jpg",
	"img/scenes/C_ES4_p4.jpg",
	"img/scenes/C_ES4_p5.jpg",
	"img/scenes/C_ES4_p6.jpg",
	"img/scenes/C_ES4_p7.jpg",
	"img/scenes/C_ES4_p8.jpg",

	"img/scenes/C_MS5_p1.jpg",
	"img/scenes/C_MS5_p2.jpg",
	"img/scenes/C_MS5_p3.jpg",
	"img/scenes/C_MS5_p4.jpg",
	"img/scenes/C_MS5_p5.jpg",
	"img/scenes/C_MS5_p6.jpg",
	"img/scenes/C_MS5_p7.jpg",
	"img/scenes/C_MS5_p8.jpg",
	"img/scenes/C_MS5_p9.jpg",

	"img/scenes/C_MS5_Foot_p1.jpg",
	"img/scenes/C_MS5_Foot_p2.jpg",
	"img/scenes/C_MS5_Foot_p3.jpg",
	"img/scenes/C_MS5_Foot_p4.jpg",
	"img/scenes/C_MS5_Foot_p5.jpg",
	"img/scenes/C_MS5_Foot_p6.jpg",
	"img/scenes/C_MS5_Foot_p7.jpg",
	"img/scenes/C_MS5_Foot_p8.jpg",
	"img/scenes/C_MS5_Foot_p9.jpg",
	"img/scenes/C_MS5_Foot_p9a.jpg",
	"img/scenes/C_MS5_Foot_p11.jpg",
	"img/scenes/C_MS5_Foot_p12.jpg",
	"img/scenes/C_MS5_Foot_p13.jpg",
	"img/scenes/C_MS5_Foot_p14.jpg",
	"img/scenes/C_MS5_Foot_p15.jpg",
	"img/scenes/C_MS5_Foot_p16.jpg",
	"img/scenes/C_MS5_Foot_p16a.jpg",
	"img/scenes/C_MS5_Foot_p17.jpg",

	"img/scenes/S_MS1_p1.jpg",
	"img/scenes/S_MS1_p2.jpg",
	"img/scenes/S_MS1_p3.jpg",
	"img/scenes/S_MS1_p4.jpg",

	"img/scenes/S_AS1_p1.jpg",
	"img/scenes/S_AS1_p2.jpg",

	"img/scenes/S_NSS_p1.jpg",
	"img/scenes/S_NSS_p2.jpg",

	"img/scenes/S_NSS_hand_p1.jpg",
	"img/scenes/S_NSS_hand_p2.jpg",
	"img/scenes/S_NSS_hand_p3.jpg",
	"img/scenes/S_NSS_hand_p4.jpg",
	"img/scenes/S_NSS_hand_p5.jpg",

	"img/scenes/S_NSS_mouth_p1.jpg",
	"img/scenes/S_NSS_mouth_p2.jpg",
	"img/scenes/S_NSS_mouth_p3.jpg",
	"img/scenes/S_NSS_mouth_p4.jpg",
	"img/scenes/S_NSS_mouth_p5.jpg",
	"img/scenes/S_NSS_mouth_p6.jpg",
	"img/scenes/S_NSS_mouth_p7.jpg",

	"img/scenes/S_NSS_pussy_p1.jpg",
	"img/scenes/S_NSS_pussy_p2.jpg",
	"img/scenes/S_NSS_pussy_p3.jpg",
	"img/scenes/S_NSS_pussy_p4.jpg",
	"img/scenes/S_NSS_pussy_p5.jpg",
	"img/scenes/S_NSS_pussy_p6.jpg",
	"img/scenes/S_NSS_pussy_p7.jpg",

	"img/scenes/S_NSS_thigh_p1.jpg",
	"img/scenes/S_NSS_thigh_p2.jpg",
	"img/scenes/S_NSS_thigh_p3.jpg",
	"img/scenes/S_NSS_thigh_p4.jpg",
	"img/scenes/S_NSS_thigh_p5.jpg",
	"img/scenes/S_NSS_thigh_p6.jpg",
	"img/scenes/S_NSS_thigh_p6a.jpg",

	"img/scenes/S_MS3_p1.jpg",
	"img/scenes/S_MS3_p2.jpg",
	"img/scenes/S_MS3_p3.jpg",
	"img/scenes/S_MS3_p4.jpg",
	"img/scenes/S_MS3_p5.jpg",
	"img/scenes/S_MS3_p6.jpg",
	"img/scenes/S_MS3_p7.jpg",

	"img/scenes/S_AS2_p1.jpg",
	"img/scenes/S_AS2_p2.jpg",
	"img/scenes/S_AS2_p3.jpg",
	"img/scenes/S_AS2_p4.jpg",

	"img/scenes/S_NS1_p1.jpg",
	"img/scenes/S_NS1_p2.jpg",
	"img/scenes/S_NS1_p3.jpg",
	"img/scenes/S_NS1_p4.jpg",
	"img/scenes/S_NS1_p5.jpg",
	"img/scenes/S_NS1_p6.jpg",
	"img/scenes/S_NS1_p7.jpg",
	"img/scenes/S_NS1_p8.jpg",
	"img/scenes/S_NS1_p9.jpg",
	"img/scenes/S_NS1_p10.jpg",
	"img/scenes/S_NS1_p11.jpg",
	"img/scenes/S_NS1_p12.jpg",
	"img/scenes/S_NS1_p13.jpg",
	"img/scenes/S_NS1_p14.jpg",
	"img/scenes/S_NS1_p15.jpg",
	"img/scenes/S_NS1_p16a.jpg",
	"img/scenes/S_NS1_p17.jpg",
	"img/scenes/S_NS1_p18.jpg",
	"img/scenes/S_NS1_p19.jpg",


	"img/scenes/S_AS3_p1.jpg",
	"img/scenes/S_AS3_p2.jpg",
	"img/scenes/S_AS3_p3.jpg",
	"img/scenes/S_AS3_p4.jpg",
	"img/scenes/S_AS3_p5.jpg",
	"img/scenes/S_AS3_p6.jpg",
	"img/scenes/S_AS3_p7.jpg",
	"img/scenes/S_AS3_p8.jpg",
	"img/scenes/S_AS3_p9.jpg",
	"img/scenes/S_AS3_p10.jpg",
	"img/scenes/S_AS3_p11.jpg",
	"img/scenes/S_AS3_p12.jpg",
	"img/scenes/S_AS3_p13.jpg",
	"img/scenes/S_AS3_13a.jpg",
	"img/scenes/S_AS3_p13b.jpg",
	"img/scenes/S_AS3_p13c.jpg",
	"img/scenes/S_AS3_p13d.jpg",
	"img/scenes/S_AS3_p13e.jpg",
	"img/scenes/S_AS3_p14.jpg",
	"img/scenes/S_AS3_p15.jpg",
	"img/scenes/S_AS3_p16.jpg",
	"img/scenes/S_AS3_p17.jpg",
	"img/scenes/S_AS3_p18.jpg",
	"img/scenes/S_AS3_p19.jpg",
	"img/scenes/S_AS3_p20.jpg",
	"img/scenes/S_AS3_p21.jpg",
	"img/scenes/S_AS3_p22.jpg",
	"img/scenes/S_AS3_p23.jpg",
	"img/scenes/S_AS3_p24.jpg",
	"img/scenes/S_AS3_p25.jpg",
	"img/scenes/S_AS3_p26.jpg",
	"img/scenes/S_AS3_p27.jpg",
	"img/scenes/S_AS3_p28.jpg",
	"img/scenes/S_AS3_p29.jpg",
	"img/scenes/S_AS3_p30.jpg",
	"img/scenes/S_AS3_p31a.jpg",
	"img/scenes/S_AS3_p31b.jpg",
	"img/scenes/S_AS3_p32.jpg",
	"img/scenes/S_AS3_p33r.jpg",
	"img/scenes/S_AS3_p34.jpg",
	"img/scenes/S_AS3_p35.jpg",
	"img/scenes/S_AS3_p36.jpg",
	"img/scenes/S_AS3_p37.jpg",
	"img/scenes/S_AS3_p37a.jpg",
	"img/scenes/S_AS3_p38.jpg",
	"img/scenes/S_AS3_p43.jpg",
	"img/scenes/S_AS3_p44.jpg",
	"img/scenes/S_AS3_p45.jpg",
	"img/scenes/S_AS3_p47.jpg",
	"img/scenes/S_AS3_p48.jpg",
	"img/scenes/S_AS3_p50.jpg",
	"img/scenes/S_AS3_p51.jpg",
	"img/scenes/S_AS3_p52.jpg",
	"img/scenes/S_AS3_p53.jpg",
	"img/scenes/S_AS3_p54.jpg",
	"img/scenes/S_AS3_p55.jpg",
	"img/scenes/S_AS3_p56.jpg",
	"img/scenes/S_AS3_p57.jpg",

	"img/scenes/S_AS3_p40r.jpg",
	"img/scenes/S_AS3_p41r.jpg",
	"img/scenes/S_AS3_p41rr.jpg",
	"img/scenes/S_AS3_p42r.jpg",
	// Character Images
	//"img/characters/",

	// Side Images
	//"img/characters/",

	// UI Images
	//"img/ui/",

	// Music Audio
	// "audio/music/",

	// Voice Audio
	// "audio/voice/"

	// Sound Audio
	// "audio/sound/"
];

self.addEventListener("install", function (event) {
	event.waitUntil(
		caches.open(`${name}-v${version}`).then(function (cache) {
			return cache.addAll(files);
		})
	);
});

self.addEventListener("activate", function (event) {
	event.waitUntil(
		caches.keys().then(function (keyList) {
			return Promise.all(keyList.map(function (key) {
				if (key !== `${name}-v${version}`) {
					return caches.delete(key);
				}
			}));
		})
	);

	return self.clients.claim();
});

self.addEventListener("fetch", function (event) {
	if (event.request.method !== "GET") {
		return;
	}

	event.respondWith(
		caches.match(event.request).then(function (cached) {
			var networked = fetch(event.request)
							.then(fetchedFromNetwork, unableToResolve)
							.catch(unableToResolve);
			return cached || networked;

			function fetchedFromNetwork (response) {
				var cacheCopy = response.clone();

				caches.open(`${name}-v${version}`).then(function add (cache) {
					cache.put(event.request, cacheCopy);
				});

				return response;
			}

			function unableToResolve () {
				return new Response("<h1>Service Unavailable</h1>", {
					status: 503,
					statusText: "Service Unavailable",
					headers: new Headers({
						"Content-Type": "text/html"
					})
				});
			}
		})
	);
});
